export const ALL_PUBLIC_MOVIE = "ALL_PUBLIC_MOVIE";
export const RETRIEVE_PUBLIC_MOVIES = "RETRIEVE_PUBLIC_MOVIES";

export const CREATE_MOVIES = "CREATE_MOVIES";
export const RETRIEVE_MOVIES = "RETRIEVE_MOVIES";
export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const DELETE_MOVIES = "DELETE_MOVIES";
export const DELETE_ALL_MOVIES = "DELETE_ALL_MOVIES";

// Auth
export const AUTH_LOGIN = "AUTH_LOGIN";
